version: "3"
services:
  db:
    image: mysql:8
    container_name: mysql_eight
    ports:
      - 3306:3306
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8",
        "--collation-server=utf8_general_ci",
      ]
    volumes:
      - mysqldata:/var/lib/mysql
      - .docker/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_DATABASE: nest
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
      MYSQL_ROOT_PASSWORD: root

  app:
    build: .
    container_name: nest_dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: nest
      DB_PASSWORD: nest
      DB_DATABASE: nest
    depends_on:
      - db

  aws:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=dynamodb
      - KINESIS_PROVIDER=kinesalite
    ports:
      - '4566:4566'
    volumes:
      - localstack:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mysqldata:
  localstack: